#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SocialBeacon.Resource", IsApplication=true)]

namespace SocialBeacon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int country_codes = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int country_names = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CFLAG_AAA = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CFLAG_Afghanistan = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CFLAG_Albania = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CFLAG_Algeria = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CFLAG_American_Samoa = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CFLAG_Andorra = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CFLAG_Angola = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CFLAG_Anguilla = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int CFLAG_Antigua_and_Barbuda = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CFLAG_Argentina = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int CFLAG_Armenia = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CFLAG_Aruba = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CFLAG_Australia = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int CFLAG_Austria = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int CFLAG_Azerbaijan = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int CFLAG_Bahamas = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CFLAG_Bahrain = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int CFLAG_Bangladesh = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int CFLAG_Barbados = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int CFLAG_Belarus = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int CFLAG_Belgium = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int CFLAG_Belize = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int CFLAG_Benin = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int CFLAG_Bermuda = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int CFLAG_Bhutan = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int CFLAG_Bolivia = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int CFLAG_Bosnia = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int CFLAG_Botswana = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int CFLAG_Brazil = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int CFLAG_British_Virgin_Islands = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int CFLAG_Brunei = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int CFLAG_Bulgaria = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int CFLAG_Burkina_Faso = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int CFLAG_Burundi = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int CFLAG_Cambodia = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int CFLAG_Cameroon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int CFLAG_Canada = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int CFLAG_Cape_Verde = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int CFLAG_Cayman_Islands = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int CFLAG_Central_African_Republic = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int CFLAG_Chad = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int CFLAG_Chile = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int CFLAG_China = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int CFLAG_Christmas_Island = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int CFLAG_Colombia = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int CFLAG_Comoros = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int CFLAG_Cook_Islands = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int CFLAG_Costa_Rica = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int CFLAG_Croatia = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int CFLAG_Cuba = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int CFLAG_Cyprus = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int CFLAG_Czech_Republic = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int CFLAG_Denmark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int CFLAG_Djibouti = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int CFLAG_Dominica = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int CFLAG_Dominican_Republic = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int CFLAG_Ecuador = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int CFLAG_Egypt = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int CFLAG_El_Salvador = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int CFLAG_Equatorial_Guinea = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int CFLAG_Eritrea = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int CFLAG_Estonia = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int CFLAG_Ethiopia = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int CFLAG_Falkland_Islands = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int CFLAG_Faroe_Islands = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int CFLAG_Fiji = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int CFLAG_Finland = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int CFLAG_France = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int CFLAG_French_Polynesia = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int CFLAG_Gabon = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int CFLAG_Gambia = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int CFLAG_Georgia = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int CFLAG_Germany = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int CFLAG_Ghana = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int CFLAG_Gibraltar = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int CFLAG_Greece = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int CFLAG_Greenland = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int CFLAG_Grenada = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int CFLAG_Guam = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int CFLAG_Guatemala = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int CFLAG_Guinea = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int CFLAG_Guinea_Bissau = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int CFLAG_Guyana = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int CFLAG_Haiti = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int CFLAG_Honduras = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int CFLAG_Hong_Kong = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int CFLAG_Hungary = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int CFLAG_Iceland = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int CFLAG_India = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int CFLAG_Indonesia = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int CFLAG_Iran = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int CFLAG_Iraq = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int CFLAG_Ireland = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int CFLAG_Israel = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int CFLAG_Italy = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int CFLAG_Jamaica = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int CFLAG_Japan = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int CFLAG_Jordan = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int CFLAG_Kazakhstan = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int CFLAG_Kenya = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int CFLAG_Kiribati = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int CFLAG_Kuwait = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int CFLAG_Kyrgyzstan = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int CFLAG_Laos = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int CFLAG_Latvia = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int CFLAG_Lebanon = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int CFLAG_Lesotho = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int CFLAG_Liberia = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int CFLAG_Libya = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int CFLAG_Liechtenstein = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int CFLAG_Lithuania = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int CFLAG_Luxembourg = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int CFLAG_Macao = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int CFLAG_Macedonia = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int CFLAG_Madagascar = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int CFLAG_Malawi = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int CFLAG_Malaysia = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int CFLAG_Maldives = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int CFLAG_Mali = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int CFLAG_Malta = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int CFLAG_Marshall_Islands = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int CFLAG_Martinique = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int CFLAG_Mauritania = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int CFLAG_Mauritius = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int CFLAG_Mexico = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int CFLAG_Micronesia = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int CFLAG_Moldova = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int CFLAG_Monaco = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int CFLAG_Mongolia = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int CFLAG_Montserrat = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int CFLAG_Morocco = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int CFLAG_Mozambique = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int CFLAG_Myanmar = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int CFLAG_Namibia = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int CFLAG_Nauru = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int CFLAG_Nepal = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int CFLAG_Netherlands = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int CFLAG_Netherlands_Antilles = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int CFLAG_New_Zealand = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int CFLAG_Nicaragua = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int CFLAG_Niger = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int CFLAG_Nigeria = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int CFLAG_Niue = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int CFLAG_Norfolk_Island = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int CFLAG_North_Korea = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int CFLAG_Norway = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int CFLAG_Oman = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int CFLAG_Pakistan = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int CFLAG_Palau = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int CFLAG_Panama = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int CFLAG_Papua_New_Guinea = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int CFLAG_Paraguay = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int CFLAG_Peru = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int CFLAG_Philippines = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int CFLAG_Pitcairn_Islands = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int CFLAG_Poland = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int CFLAG_Portugal = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int CFLAG_Puerto_Rico = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int CFLAG_Qatar = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int CFLAG_Romania = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int CFLAG_Russian_Federation = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int CFLAG_Rwanda = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int CFLAG_Saint_Kitts_and_Nevis = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int CFLAG_Saint_Lucia = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int CFLAG_Saint_Pierre = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int CFLAG_Saint_Vicent_and_the_Grenadines = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int CFLAG_Samoa = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int CFLAG_San_Marino = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int CFLAG_Saudi_Arabia = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int CFLAG_Senegal = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int CFLAG_Serbia_and_Montenegro = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int CFLAG_Seychelles = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int CFLAG_Sierra_Leone = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int CFLAG_Singapore = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int CFLAG_Slovakia = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int CFLAG_Slovenia = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int CFLAG_Soloman_Islands = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int CFLAG_Somalia = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int CFLAG_South_Africa = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int CFLAG_South_Georgia = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int CFLAG_South_Korea = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int CFLAG_Spain = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int CFLAG_Sri_Lanka = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int CFLAG_Sudan = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int CFLAG_Suriname = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int CFLAG_Swaziland = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int CFLAG_Sweden = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int CFLAG_Switzerland = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int CFLAG_Syria = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int CFLAG_Taiwan = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int CFLAG_Tajikistan = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int CFLAG_Tanzania = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int CFLAG_Thailand = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int CFLAG_Timor_Leste = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int CFLAG_Togo = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int CFLAG_Tonga = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int CFLAG_Trinidad_and_Tobago = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int CFLAG_Tunisia = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int CFLAG_Turkey = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int CFLAG_Turkmenistan = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int CFLAG_Turks_and_Caicos_Islands = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int CFLAG_Tuvalu = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int CFLAG_Uganda = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int CFLAG_Ukraine = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int CFLAG_United_Kingdom = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int CFLAG_United_States_of_America = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int CFLAG_Uruguay = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int CFLAG_Uzbekistan = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int CFLAG_Vanuatu = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int CFLAG_Vatican_City = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int CFLAG_Venezuela = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int CFLAG_Vietnam = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int CFLAG_Wallis_and_Futuna = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int CFLAG_Yemen = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int CFLAG_Zambia = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int CFLAG_Zimbabwe = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int default_profile_pic = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int logo = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int manutza = 2130837722;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060019
			public const int aboutET = 2131099673;
			
			// aapt resource value: 0x7f060021
			public const int aboutTV = 2131099681;
			
			// aapt resource value: 0x7f060011
			public const int ageET = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int ageTV = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int backBtn = 2131099682;
			
			// aapt resource value: 0x7f06001b
			public const int cancelBtn = 2131099675;
			
			// aapt resource value: 0x7f060003
			public const int centerline = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int chat = 2131099656;
			
			// aapt resource value: 0x7f060025
			public const int chatBtn = 2131099685;
			
			// aapt resource value: 0x7f06000d
			public const int chatList = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int chatMessages = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int chatMsg = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int cityET = 2131099669;
			
			// aapt resource value: 0x7f06001e
			public const int cityTV = 2131099678;
			
			// aapt resource value: 0x7f060026
			public const int clientSwitch = 2131099686;
			
			// aapt resource value: 0x7f060014
			public const int countrySPN = 2131099668;
			
			// aapt resource value: 0x7f06001d
			public const int countryTV = 2131099677;
			
			// aapt resource value: 0x7f060006
			public const int drawerLayout = 2131099654;
			
			// aapt resource value: 0x7f060023
			public const int editInfoBtn = 2131099683;
			
			// aapt resource value: 0x7f060018
			public const int emailET = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int emailTV = 2131099680;
			
			// aapt resource value: 0x7f06000f
			public const int firstNameET = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int firstNameTV = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int flag = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int frame = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int lastNameET = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int lastNameTV = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int manutzaFL = 2131099655;
			
			// aapt resource value: 0x7f060028
			public const int myDif = 2131099688;
			
			// aapt resource value: 0x7f06000e
			public const int personName = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int phoneET = 2131099671;
			
			// aapt resource value: 0x7f06001f
			public const int phoneTV = 2131099679;
			
			// aapt resource value: 0x7f060000
			public const int profilePic = 2131099648;
			
			// aapt resource value: 0x7f06001a
			public const int saveBtn = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int sendBtn = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int sendMsgBox = 2131099658;
			
			// aapt resource value: 0x7f060024
			public const int serverNameTV = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int serversList = 2131099687;
			
			// aapt resource value: 0x7f060012
			public const int tableRow1 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int textView1 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int textView2 = 2131099670;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChatListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FriendChatBubble = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int InfoEditForm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InfoViewForm = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyChatBubble = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
